server:
  error:
    whitelabel:
      enabled: false
  port: 8080
  shutdown: graceful
  tomcat:
    connection-timeout: 5s
  servlet:
    context-path: /cjconnect/admin/api
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    application-display-name: cjconnect-admin-api

management:
  metrics:
    tags:
      application: api-admin
